$(document).on('click', ".checkout", function(){

var time = updateClock();
$('.page-container').html('<div class="header navbar-fixed-top"> <nav class="navbar fluid-container"> <div class="navbar-header"> <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button> <img id="logo logo_icon" src="img/icon_trans.png" alt="expfood"> <img id="logo" src="img/logo_main.png" alt="expfood"> </div> <div class="navbar-collapse collapse navbar-right"> </div> </nav> </div> <div class="container"> <div class="jumbotron content"> <form class="form-horizontal"> <div class="form-group"> <label for="inputEmail3" class="col-sm-2 control-label">Адрес</label> <div class="col-sm-10"> <input type="text" required class="form-control" id="inputEmail3" placeholder="Например Маковского 2"> </div> </div> <div class="form-group"> <label for="inputPassword3" class="col-sm-2 control-label">Ваше Имя</label> <div class="col-sm-10"> <input type="text" class="form-control" id="inputPassword3" placeholder="Например Маша"> </div> </div> <div class="form-group"> <label for="inputPassword3" class="col-sm-2 control-label">Номер мобильного</label> <div class="col-sm-10"> <input type="text" required class="form-control" id="inputPassword3" placeholder="По нему мы будем звязываться с Вами по всем вопросам заказа"> </div> </div> <div class="form-group"> <label for="inputPassword3" class="col-sm-2 control-label" >Дополнительные инструкции</label> <div class="col-sm-10"> <textarea class="form-control" rows="3" placeholder="Позвонить когда доставят"></textarea> <!-- <input type="text" class="form-control" id="inputPassword3" placeholder="Позвонить когда доставят"> --> </div> </div> <div class="form-group"> <label for="inputPassword3" class="col-sm-2 control-label">Доставим сегодня до </label> <div type="text" class="col-sm-10 order-time"> '+time[0]+':'+time[1]+' </div> </div> <div class="form-group"> <label for="inputPassword3" class="col-sm-2 control-label">Итого к оплате </label> <div type="text" class="col-sm-10 order-price"> '+totalCost+' рублей</div> </div> <div class="form-group"> <div class="form-group"> <div class="col-sm-offset-2 col-sm-10"> <button type="submit" class="btn btn-large btn-success">Sign in</button> </div> </div> <div class="col-sm-offset-2 col-sm-10"> <iframe frameborder="0" allowtransparency="true" scrolling="no" src="https://money.yandex.ru/embed/small.xml?account=410013034873931&quickpay=small&any-card-payment-type=on&button-text=02&button-size=l&button-color=white&targets=expfood&default-sum=999&successURL=" width="195" height="54"></iframe> </div> </div> </form> </div> </div>  <link rel="stylesheet" type="text/css" href="css/index.css"> <link rel="stylesheet" type="text/css" href="css/order.css">')


$( "iframe" ).attr({
	  src: "https://money.yandex.ru/embed/small.xml?account=410013034873931&quickpay=small&any-card-payment-type=on&button-text=02&button-size=l&button-color=white&targets=expfood&default-sum="+totalCost+"&successURL=",
	});

});